### ISSUE TITLE
mock-express available for use

### ISSUE THREAD

**Issue by scottnath** [howardabrams/node-mocks-http#103]
Hi team,

I would like to use [mock-express](https://github.com/howardabrams/node-mocks-http/tree/master/lib/express) to test out some init files in my Express.js application. These init files, among other functions, send my express app through app.use ([example](https://github.com/punchcard-cms/punchcard/blob/a30e5c2ecc8b9072d671365bcc802e9c5b03ef40/lib/init/logger.js).)

I don't see a way to access mock-express.js. I've tried things like `node-mocks-http/lib/express/mock-express`, but then that fails with errors like: 

`Error: Cannot find module './node/http'`

Could I create a PR to add mock-express into the `exports` at the bottom of `/lib/http-mock.js`?

```
var response = require('./mockResponse');
var express = require('./express/mock-express');

...

exports.createResponse = response.createResponse;
exports.createExpress = express;
exports.createMocks = createRequestResponse;
```

Have you tried this and would that simple change open up mock-express to be used, or would there be more changes that would be required to mock up my Express application?

thanks,
Scott

**Comment by scottnath** [comment]
@howardabrams I took a stab at opening this up, but it seems like a lot of the dependencies for it were not in `package.json`. Is that because the mock-express section is not  yet complete?

thanks,
Scott

**Comment by howardabrams** [comment]
Yeah. Feel free to make whatever changes are necessary in your PR, and then we can talk about a way to make this work for existing users. Thanks!
