### ISSUE TITLE
Please remove lodash.assign

### ISSUE THREAD

**Issue by PepijnSenders** [howardabrams/node-mocks-http#108]
Your package is depending on: `lodash.assign` which was recently deprecated.

The warning:

```
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
```

The tree:

```
├─┬ node-mocks-http@1.5.4
│ ├── lodash.assign@4.2.0
```

Please refactor accordingly.

**Comment by IgorAufricht** [comment]
I noticed the same thing, but I'm not sure if this is by design or by mistake, so I created an issue for lodash developers:
https://github.com/lodash/lodash/issues/2701
