### ISSUE TITLE
can't send an empty response with status 204 No Content?

### ISSUE THREAD

**Issue by devanshug** [howardabrams/node-mocks-http#109]
I am trying to work on some REST APIs, but a specific test case fails because I am getting the error
`Unexpected end of JSON input`
I have checked the API is working fine, only the test case part where node-mocks-http is used fails. Sending empty response is supported in express module. Is this behaviour kept this way, or I am missing something here.

**Comment by devanshug** [comment]
Found a problem in my test case, I was trying to parse the response.
`let body = JSON.parse(res._getData())`

**Comment by howardabrams** [comment]
Great. Glad you were able to solve it.

**Comment by migudonatien** [comment]
I have same issue when using _getData or _getJSONData.

> `SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)

      128 |     await controller.getAdvisorStatus(req, res, next);
      129 |     expect(next).toHaveBeenCalledTimes(1);
    > 130 |     const data = res._getJSONData();
          |                      ^
      131 |     expect(data).toHaveProperty('Error', 'Invalid signature');
      132 |   });
      133 | });
`

**Comment by cristhian-net** [comment]
> Em... having same problems like the guys above. @devanshug parsing the response is a correct thing to do, right? It's both logical and shown in the docs

For anyone having this problem, you probably need to check if you are returning a value for your mocks `mockedFunction.mockReturnValue(something)`
