### ISSUE TITLE
Get more people involved with maintaining this project

### ISSUE THREAD

**Issue by howardabrams** [howardabrams/node-mocks-http#110]
I put together this package when the company I was employed was building a node-based project. That project is over and I'm no longer with that company either. I'm sorry to say that I currently have no Node-based projects, and consequently don't use this mocking project. Since it is useful to a lot of people, I don't want it to become abandonware.

I'm reaching out to the community to see if they would like to help monitor and review changes to this code base... essentially join the team. Perhaps by expanding the team would be less of a commitment? If you are interested in helping out, please contact and I'll add you to the Slack team.

**Comment by manojkrishna1991** [comment]
HI @howardabrams I am interested can you add me to this project
