### ISSUE TITLE
No `finish` event, `end` event called when it shouldn't be.

### ISSUE THREAD

**Issue by SeanHayes** [howardabrams/node-mocks-http#112]
I noticed a discrepancy between my handlers running in a live env and running during tests. In test using a mock response the `end` event gets called, but it doesn't get called in production. The node docs say that the `end` event should only get called when the stream is in flowing mode: https://nodejs.org/api/stream.html#stream_event_end

Conversely, in a live env the `finish` event gets fired on my responses, but not on mock responses.

**Comment by eugef** [comment]
`finish` event is fired with the latest version of package
