### ISSUE TITLE
req.subdomains is not defined

### ISSUE THREAD

**Issue by tallytarik** [howardabrams/node-mocks-http#117]
Just wanted to start off by saying thanks for an awesome project! I've just started using this to test some middleware and I'm having some issues because `req.subdomains` isn't defined, and I'm testing some middleware that checks the current subdomain.

I've been having a browse and I can see in ./express/mock-request.js it looks like it's implemented the same way Express implements it, but it looks like this isn't used - would the subdomain property have to be added to  ./mockRequest.js? Happy to submit a PR if I can be pointed in the right direction!

**Comment by howardabrams** [comment]
A PR would be great. Do you have personal test cases that expose this
deficiency?
