### ISSUE TITLE
'end' event is triggered twice

### ISSUE THREAD

**Issue by tomi** [howardabrams/node-mocks-http#119]
Starting from v1.5.5 'end' event can be triggered twice for the mocked response. In v1.5.4 it was triggered only once.

```javascript
var mockedRes = httpMocks.createResponse({
  eventEmitter: EventEmitter
});

mockedRes.on("end", function() {
  // I would expect this is never called twice 
  ...
});
```

**Comment by fidian** [comment]
@tomi Does my fix correct the problem you were experiencing?

**Comment by tomi** [comment]
@fidian Yes, the problem doesn't appear anymore with the latest version 1.6.1
