### ISSUE TITLE
Add .headersSent to mockResponse

### ISSUE THREAD

**Issue by robballou** [howardabrams/node-mocks-http#12]
The Node ServerResponse class has a property for detecting if headers have been sent:

http://nodejs.org/api/http.html#http_response_headerssent

This would be great if it were supported by this module. Thanks!

**Comment by JohnnyEstilles** [comment]
@robballou, I know this issue is a bit old, but I think it would be a great addition to the project. I'm going to work on a PR to add this feature.

**Comment by JohnnyEstilles** [comment]
Deferring fix for this issue until `v2.0`.
