### ISSUE TITLE
Restify and response.header()

### ISSUE THREAD

**Issue by fidian** [howardabrams/node-mocks-http#121]
The Restify framework allows one to retrieve a header's value from the response by using `res.header("name")`.  The expected return value is the header's value.  This is not possible with the current node-mocks-http module.  The problem comes up when I use restify-cookies to set cookies on the response.  It uses `res.header("Set-Cookie")` to retrieve the current value so it can append additional cookies.

I've patched the header function to support this additional mechanism with the following code.  Currently I am modifying the `res` object that's returned from your module as opposed to modifying the prototype.

    // The res.header() function does not operate in a similar fashion to
    // how Restify's version works.  Restify allows for a single string
    // input and this returns the value.  We monkey patch the response
    // object to behave similarly.
    originalHeader = res.header;
    res.header = (key, val) => {
        if (!val && typeof key === "string") {
            return res.getHeader(key);
        }

        return originalHeader.call(res, key, val);
    };

This seems to work fine for me.  Is this something that could get adopted into node-mocks-http so I don't need to patch the function?

**Comment by howardabrams** [comment]
Just extending functionality, seems reasonable. Can you make a PR with a test to demonstrate it? Thanks!

**Comment by fidian** [comment]
I have done as you asked.

**Comment by howardabrams** [comment]
Great. Thanks. Do you have time to get the unit tests working, and then I'll merge it.

**Comment by fidian** [comment]
At this point I am starting to question your dedication to the project.  I made no complaints about the tests and they ran successfully when I used `npm test`.  There were no linting problems when `npm test` finished on my machine, or at least none that I can recall.  I take it that you don't want to change the quoting style yourself and eliminate the `else`?

If I get back to a computer sometime, I may change the pull request to pass the linting.  Doing such things on a phone is tedious.

**Comment by fidian** [comment]
This was resolved when pull request #123 was merged.

**Comment by howardabrams** [comment]
Your point about dedication isn't far off. I don't use Node anymore, and have no projects that do, so I'm not sure how to expand or address the deficiencies in this project. I am looking for either helper volunteers or someone to take over shepherding this project, so if you know of someone, point them my way.

Thanks for understanding.

**Comment by fidian** [comment]
I don't think I have the time to take on another project, but I submitted some pull requests with the intent of helping a bit with yours.
