### ISSUE TITLE
mockResponse.cookie does not follow the builder pattern

### ISSUE THREAD

**Issue by danallen88** [howardabrams/node-mocks-http#129]
If my code under test has something like `res.status(200).cookie('name', 'value').send('stuff')`, then the `send` method will never get called (and consequently the `end` event will not fire) because the mockResponse.cookie method does not support chaining.

```
mockResponse.cookie = function(name, value, opt) {

        mockResponse.cookies[name] = {
            value: value,
            options: opt
        };

    };
```
I suspect this could be fixed by ending the method with `return this;`

**Comment by howardabrams** [comment]
Interesting idea. We would probably want all other functions to do that too.

Can't think of what would be the downside to this. This shouldn't break backward compatibility, would it?

**Comment by danallen88** [comment]
I wouldn't think it would break backward compatibility.  We would just want to be careful to only implement it for express methods that support chaining.  If I get some free time I'd be happy to submit a PR.
