### ISSUE TITLE
How can I set res.locals?

### ISSUE THREAD

**Issue by takehilo** [howardabrams/node-mocks-http#132]
My production code is like the following:

```
res.locals.flash = {
  type: 'danger',
  message: 'error'
};

res.status(400)
return res.render('index');
```

How can I set `res.locals` using `httpMocks.createResponse`?
It would be nice if I could set any property as `httpMocks.createRequest` does:

```
httpMocks.createResponse({
  locals: {}
});
```

Thank you.

**Comment by takehilo** [comment]
A simple way is just adding `locals` property but are there any other ways to do this?

```
const res = httpMocks.createResponse();
res.locals = {};
```

**Comment by howardabrams** [comment]
Hopefully, version 1.6.2 will solve your problem.

**Comment by eugef** [comment]
Version 1.6.6 si still missing this feature

**Comment by ecg-trial** [comment]
Version > 1.6.6 should have this fixed

**Comment by eugef** [comment]
Version > 1.6.6 should have this fixed
