### ISSUE TITLE
Unable to retrieve stream content

### ISSUE THREAD

**Issue by unusualbob** [howardabrams/node-mocks-http#139]
I was attempting to use this library for testing a few endpoints, however I've hit a snag when attempting to use it with endpoints which pipe their response.
Ie something like:
```js
//Server side
app.post('/someUrl', function(req, res) {
  MyDbResultStream.pipe(res);
});

/*=====*/

//Test client
function generateMock(method, url, data, headers, callback) {
  var req = httpMock.createRequest({
    method: method,
    url: url,
    body: data,
    headers: _.extend({
      'content-type': 'application/json',
      'referrer': 'https://' + config.hostAndPort,
      'host': config.hostAndPort
    }, headers),
    session: {}
  });

  var res = httpMock.createResponse({
    eventEmitter: emitter
  });
  res.on('end', function () {
    var data = res._getData();
    res.emit('done', data);
  });
  callback(req, res);
}

generateMock('POST', 'someUrl', {my: 'body'}, {apiKey: '1234'}, function(req, res) {
  res.on('done', function(response) {
    console.log(response); //empty string
  });
  myApp.handle(req, res);
});
```

I've tried creating my own writeable stream and passing that in as an option, however nothing gets written to it. I know the server side is correct as I can execute the same request from a browser/curl and get a proper stream of results. Does this library not actually capture stream write events or am I missing something?

**Comment by howardabrams** [comment]
This library simulates a "server for a client" (if that makes sense), so it pretends to be a server, so it never interacts with a real server...just your client code. Yes, I am only stating this for others, so that they understand.

In your particular case, I believe I'm missing some code. A server that pipes the code still delivers the code as an HTTP response, correct? Are you wanting to simulate a delay from the server, or chunked delivery?

**Comment by unusualbob** [comment]
I've used this for other routes, ie standard `res.send({test: 'ok'});` with no issues. However when I attempted to test a route which used streams as shown here I was unable to get any data.

There is no code missing here, you can simply pipe any compatible node stream to `res` and the data will automatically be chunked as necessary and transmitted to the client. The issue is that with a real client I will receive the payload, but with this library no result was returned.

It's been a long time so I don't remember the details. I know I tried a few different configurations of res here and was unable to get one that worked, the one I submitted above seemed the most sane. I have since switched libraries since its been so long, however others may find it useful to have a working example of streams if it is possible, or support for them if not currently supported.

**Comment by MaxwellGBrown** [comment]
I've run into this same issue; I'm not sure if there's a different way I should be reading piped data other than `response._getData` or if it's just not available at all?

```
// views.js
const arabesque = (request, response) => {
  const filepath = path.join(__dirname, 'static', 'arabesque_1.mp3');
  const stat = fs.statSync(filepath)

  response.writeHead(200, {
      'Content-Type': 'audio/mpeg',
      'Content-Length': stat.size
  });

  const readstream = fs.createReadStream(filepath);
  readstream.pipe(response);
};
```

```
// tests/test_views.js
test('arabesque response body is same as arabesque_1.mp3', t => {
  let request = httpMocks.createRequest();
  let response = httpMocks.createResponse();

  views.arabesque(request, response);
  // shouldn't be using toString() here but unsure how to get the response stream for comparison yet
  const arabesqueData = fs.createReadStream(
    path.join(__dirname, '..', 'app', 'static', 'arabesque_1.mp3')
  ).toString();
  const data = response._getData();
  t.is(data, arabesqueData);
});
```

```
$ npm run test

  > ava
  
  1 failed

  arabesque response body is same as arabesque_1.mp3

  /node_galore/tests/test_views.js:125

   124:   const data = response._getData();
   125:   t.is(data, arabesqueData);       
   126: });                                

  Difference:

  - ''
  + '[object Object]'
```

**Comment by morgs32** [comment]
@unusualbob what did you switch to?
