### ISSUE TITLE
sendStatus() does not return response object

### ISSUE THREAD

**Issue by coderslagoon** [howardabrams/node-mocks-http#144]
But just undefined, hence code calling e.g. `rsp.sendStatus(...).end()` will not work/crash.

**Comment by howardabrams** [comment]
I believe I'm missing something. What are you expecting this case? Thanks.

**Comment by coderslagoon** [comment]
The current implementation of sendStatus() returns the response object, so you can use it afterwards, like calling end(). However a) the Express 4 documentation doesn't mention it and b) it doesn't make much sense apparently, because sendStatus() is a final action. So I guess the current mock's fine.
