### ISSUE TITLE
Unable to get any response using response._getData()

### ISSUE THREAD

**Issue by brijeshprasad89** [howardabrams/node-mocks-http#149]
I have written the following code to fetch data from mondo db:
Route:
```
router.get('/config/:id?', (req, res) => {
    return controller.findDataById(req, res);
});
```
controller:
`mongoClient.findDataById(params, res);`

client:
```
DataModel.find({_id: params.id}).limit(1).
    then((data) => {
            return response.json(data);
    })
    .catch((err) => {
        logger.error('Error when retrieving data with id %s', params.id, err);
    });
```

I am trying to write the integration test for the same:
```
const httpMocks = require('node-mocks-http');

let request  = httpMocks.createRequest({
                method: 'GET',
        url: '/config/59cf3c6df36d286c005cc2a8',
        params: {
          id: '59cf3c6df36d286c005cc2a8'
        }
    });
 
    let response = httpMocks.createResponse();
    mongoClient.findDataById(request,response);
    let data =  response._getData();
```
I get nothing in `data`. Is there anything that I am doing wrong?

**Comment by adc17** [comment]
I think `_getData()` is an async operation—I had this issue and resolved it by wrapping the call in a timeout. I admit it's not the best solution though.

If `_getData()` is async, it would be nice if it returned a Promise.

**Comment by hephzaron** [comment]
https://github.com/howardabrams/node-mocks-http/issues/73        check this out, it works for me

**Comment by belyas** [comment]
I have got almost same issue, here's my code:

describe('Category router', () => {
    it('Returns 200 status code', () => {
        const response = buildResponse()
        const request  = httpMocks.createRequest({
            method: 'GET',
            url: '/categories/',
        });

        CategoryRouter(request, response)

        console.log('[Res:data]', response._getData());
    });
});

It's a simple get router with sychronous code, no apis.

I get this error: TypeError: Cannot read property 'apply' of undefined

Anyone can help please?

Thanks in advance
