### ISSUE TITLE
Add .originalUrl to mockRequest

### ISSUE THREAD

**Issue by TGOlson** [howardabrams/node-mocks-http#15]
My node controller parses a url form the request using the below form:

```
req.protocol + '://' + req.get('host') + req.originalUrl;
```

In order to test this, I need to send a request with the above properties, in particular the ```get``` function is required (```req.originalUrl``` will be ```undefined```, but ```req.get(...)``` will throw an error).

However, this mock library doesn't allow for the user to add these 'custom' options to the request. That feature should be added.

**Comment by JohnnyEstilles** [comment]
@TGOlson / @alanjames1987, AFAICT ... `req.get()` is already implemented (haven't gone back through the history to determine in what version) and `.createRequest()` allows you to set headers. However, `req.originalUrl` has not yet been implemented.

Will edit issue title to reflect this and will start working on a PR to implement this soon.

**Comment by JohnnyEstilles** [comment]
Implemented via #43
