### ISSUE TITLE
How to get body of data that is piped to mockResponse

### ISSUE THREAD

**Issue by morgs32** [howardabrams/node-mocks-http#152]
I respond like this:

```
function handler(req, res) {
   ...
   streamRes.pipe(res)
}
```

On `res.on('end', () => ...`
How do I get the stream or the object that was streamed?

Thanks!

**Comment by Yaty** [comment]
Did you find a solution :) ?

**Comment by morgs32** [comment]
@Yaty *first* I went with `supertest`

```
const request = require('supertest')
const app = express()
app.use(artworkRouter)  // <--- My request handler
app.use((err) => {
  console.log(err)
})
describe('artworkHandler', () => {

  it('@integration: /front/1.png', () => {

    return request(app)
      .get('/front/1.png')
      .buffer()
      .expect('Content-Type', 'image/png')
      .expect((res) => {
        expect(res.body).toMatchImageSnapshot()
      })

  })
})
```
As you can see I was using `jest` and `toMatchImageSnapshot()`.

*Later*, I switched to [test-listen](https://github.com/zeit/test-listen) by the team at [zeit](https://zeit.co/).


```
const micro = require('micro')
const listen = require('test-listen')
const axios = require('axios')
describe('@integration artworkHandler', () => {

  it('/api/artwork/front/shirt1.png', async () => {

    const service = micro(router.handler)
    const url = await listen(service)

    await axios.get(`${url}/api/artwork/front/shirt1.png`, {
      headers: {
        'Content-Type': 'image/png'
      },
      responseType: 'arraybuffer',
    })
      .then((res) => {
        expect(res.data).toMatchImageSnapshot()
      })
    service.close()

  })
})
```
This is preferable to me because it is how I use the endpoint in prod.

**Comment by rodrigoreis22** [comment]
Any solutions using this library @morgs32 ?

**Comment by morgs32** [comment]
Nope. I strongly recommend `test-listen`. Instead of figuring out how to get a mock and the mock API to work, you can use the same api you know and use everywhere (axios/fetch/whatever)?

**Comment by rodrigoreis22** [comment]
@morgs32 i was able to do this to work by using `res.on('end'` and then on the callback you use `res._getChunks()` to build back the response.
