### ISSUE TITLE
'end' event is not being triggered

### ISSUE THREAD

**Issue by amitguptagwl** [howardabrams/node-mocks-http#162]
```js
    it('should call post handler after main handler', done => {

       var request  = httpMocks.createRequest({
            method: 'GET',
            url: '/without/pre/handlers'
        });
        var response = httpMocks.createResponse({
            eventEmitter: require('events').EventEmitter
          });
        
        router.lookup(request,response);

        response.on('end', function() {
            expect(response._getData()).toEqual(" main -> post.");
            expect(response.statusCode ).toEqual(200);
            expect(response._isEndCalled()).toBe(true);
            done();
        });
    });
```

 Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL

**Comment by eugef** [comment]
Try to move `router.lookup(request,response);` below the `response.on` - event might be fired before you assign an event handler

**Comment by amitguptagwl** [comment]
Thanks. I've changed the code to following

```js
    it('should call post handler after main handler', done => {

       var request  = httpMocks.createRequest({
            method: 'POST',
            url: '/without/pre/handlers'
        });
        var response = httpMocks.createResponse({
            eventEmitter: require('events').EventEmitter
          });
        
        response.on('end', function() {
            expect(response._getData()).toEqual(" main -> post.");
            expect(response.statusCode ).toEqual(200);
            expect(response._isEndCalled()).toBe(true);
            done();
        });
        router.lookup(request,response);
    });
```

Now it is calling response 'end' event. But it's not calling request's 'data' or 'end' event

**Comment by eugef** [comment]
Are you sure request object has those events? I've checked here https://nodejs.org/docs/latest-v8.x/api/http.html#http_class_http_clientrequest and can't see that request has 'data' or 'end' events

**Comment by amitguptagwl** [comment]
Yes. if I run the server and hit the URL directly. I get the expected response. Which means all the events are being registered successfully at least in the case of direct hit.

In above example, I've also tried with 'body' property. However it is not necessary. Is there anything else I'm missing in above example that I should do?

**Comment by amitguptagwl** [comment]
In addition, I'm using node v9.5.0, and npm v5.6.0

**Comment by eugef** [comment]
Could you give an example of your code with subscribing for  'data' or 'end' request events

**Comment by amitguptagwl** [comment]
Here is the link : https://github.com/muneem4node/muneem/blob/master/src/routesMapper.js

Since it is big, it may eat your valuable time.

**Comment by amitguptagwl** [comment]
Is there any luck? 

I've recently created a new router  [अनुमार्गक (anumargak)](https://github.com/NaturalIntelligence/anumargak) but it didn't with that as well. Everything is fine when I run the server and hit the URL.

**Comment by amitguptagwl** [comment]
I've just noticed that it doesn't matter which router I'm using, it doesn't call any event on request body.

```js

function fakeRouter(req,res){
    req.on("data", chunk => {
        console.log(chunk);
    });
    res.end("kill me");
}
```

So in above code, it doesn't prints chunk. I tried to call `request.write()` but that seems invalid.

**Comment by amitguptagwl** [comment]
I got a partial solution. I need to emit the event myself after calling the lookup or method.

```js
req.emit('data', 'Hello data!');
req.emit('end');
```

I was expecting it to be the part of the code.
