### ISSUE TITLE
request.pipe is not a function

### ISSUE THREAD

**Issue by amitguptagwl** [howardabrams/node-mocks-http#166]
I was assuming that the mocked request is actually a fake stream so pipe function should be available.

**Comment by amitguptagwl** [comment]
I can raise a PR for this if you please merge my previous PR. However I strongly feel that original API should be built on top of stream not the event

**Comment by eugef** [comment]
Please raise a PR

**Comment by amitguptagwl** [comment]
Thanks @eugef  for your support. However I've been switched to some other library due to stream handling. Here is the code change for other users who faces this issue.

```js
mockRequest.send = function(data) {
        
        if(Buffer.isBuffer(data)){
        }else if(typeof data === "object" || typeof data === "number"){
            data = Buffer.from(JSON.stringify(data));
        }else if(typeof data === "string"){
            data =  Buffer.from(data);
        }
        this.emit('data', data);
        this.emit('end');
        if(this.stream){
            this.stream.end(data);
        }
    };

    mockRequest.pipe = function(dest) {
        this.stream = dest;
    };
```

Feel free to close this issue.
