### ISSUE TITLE
The latest version is not tagged correctly in npm

### ISSUE THREAD

**Issue by danielmcq** [howardabrams/node-mocks-http#168]
If you run the command `npm view node-mocks-http` you will see that the version with the *latest* tag is 1.5.8. However, version 1.6.7 seems to be the latest stable version and should probably be tagged with the *latest* tag. It would be as simple as the maintainers running the command `npm dist-tag rm node-mocks-http latest && npm-dist-tag add node-mocks-http@1.6.7 latest`.

**Comment by eugef** [comment]
@danielmcq thank you for helping - the latest version is now correct in npm
