### ISSUE TITLE
requests should be event emitters

### ISSUE THREAD

**Issue by focusaurus** [howardabrams/node-mocks-http#17]
I need to mock doing `req.on('end', onEnd);` and the mock request class does not have the event emitter methods.

**Comment by JohnnyEstilles** [comment]
@focusaurus, the `mockRequest` implementation in this project aims to mock Express' `request` class and Node's `http.IncomingMessage` (which Express' `request` extends), neither of which are event emitters.

It's possible you believe `mockRequest` mocked Node's `http.request`, which is not the case.

If you have any additional questions or comments feel free to reopen this issue.

**Comment by focusaurus** [comment]
> neither of which are event emitters.

Node's http.IncomingMessage subclasses Stream.readable as seen [here](https://github.com/joyent/node/blob/a995a6a776f1b2d01946702190c6ff837c338577/lib/_http_incoming.js#L82).

Stream.readable inherits from stream, which is an event emitter as seen [here](https://github.com/joyent/node/blob/a995a6a776f1b2d01946702190c6ff837c338577/lib/stream.js#L45)

In the repl, you can see that http.IncomingMessage clearly has an "on" function.

    new http.IncomingMessage().on
    [Function]

Streaming in node is built upon the event emitter pattern, and HTTP messages support streaming.

**Comment by JohnnyEstilles** [comment]
@focusaurus, you're absolutely right. My apologies. Let me see if I can work on implementing this.

**Comment by JohnnyEstilles** [comment]
We're scheduling this feature for our `v2.0` release.

**Comment by jvwing** [comment]
I worked around this issue by mashing an instance of [node-memorystream](https://github.com/JSBizon/node-memorystream) with node-mock-http's mockRequest. The mockRequest is then a stream, complete with event support sufficient to fool body-parser.  The end() method is used to flush the stream.

Underscore hackery aside, this seems like a reasonable approach to supporting request-as-stream.  Would a pull request for adding stream support based on [node-memorystream](https://github.com/JSBizon/node-memorystream) be welcomed?

```
var assert = require("assert");
var bodyParser = require("body-parser");
var httpMocks = require("node-mocks-http");
var MemoryStream = require("memorystream");
var _ = require("underscore");

describe("Testing form post with body-parser", function () {
    var urlEncodedParser = bodyParser.urlencoded({ "extended": false, "limit": "32kb" });
    var memStream = new MemoryStream();
    var httpMocksRequest = httpMocks.createRequest({
        "method": "POST",
        "headers": {
            "content-type": "application/x-www-form-urlencoded",
            "transfer-encoding": "chunked"
        }
    });
    var mockRequest = _.extend(memStream, httpMocksRequest);
    var mockResponse = httpMocks.createResponse();
    var nextCalled = false;
    before(function () {
        urlEncodedParser(mockRequest, mockResponse, function () {
            nextCalled = true;
        });
        mockRequest.end("name=Some+Dude&email=some.dude%40foobar.com");
    });
    it("Called Next", function () {
        assert.equal(nextCalled, true);
    });
    it("Parsed Body", function () {
        assert.equal(mockRequest.body.name, "Some Dude");
        assert.equal(mockRequest.body.email, "some.dude@foobar.com");
    });
});
```

**Comment by evanshortiss** [comment]
Hey,

I came across this also and just added the following in _mockRequest.js_:

```
var events = require('events');
var mockRequest = Object.create(events.EventEmitter.prototype);
```

This allows me to fire events on the _mockRequest_ in test cases. Happy to submit a PR.

**Comment by evanshortiss** [comment]
Here's a sample commit [link](https://github.com/evanshortiss/node-mocks-http/commit/54c96a2681371b08ede063120b4cda51e4ac86ed) with the change.
