### ISSUE TITLE
[DEP0005] DeprecationWarning: Buffer() is deprecated

### ISSUE THREAD

**Issue by vad3x** [howardabrams/node-mocks-http#204]
**Overview:**

Nodejs writes a warning to console when using the library:

```
[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Versions:**
node-mocks-http: 1.8.1
node: v12.14.0

**Suggestions:**

Use `Buffer.alloc` instead of `new Buffer`

**Comment by eugef** [comment]
@vad3x thanks for reporting
