### ISSUE TITLE
Unable to test the structured session data with typescript.

### ISSUE THREAD

**Issue by u4da3** [howardabrams/node-mocks-http#205]
I'm testing the structured session data with typescript. 
But the test does not work because of the type error.

For example, in `express-session`, the type definition of `SessionData` is as below:

```ts
interface SessionData {
  [key: string]: any;
  cookie: SessionCookieData;
}
```

But, the type definition in `node-mocks-http` is as below:

```ts
export interface Session {
  [key: string]: string;
}
```

I tyied rewriting the type definition in `node-mocks-http`: `[key: string]: string;` -> `[key: string]: any;`
And the test works successfully.

**Comment by eugef** [comment]
Hi @u4da3, would be great if you create a PR with the fix
