### ISSUE TITLE
`res.hasHeader()` not defined

### ISSUE THREAD

**Issue by gabssnake** [howardabrams/node-mocks-http#207]
Hi, thanks for your work on this module :)

What's your point of view on making assertions on headers, e.g. `res.hasHeader()`?
How would one do it while using this module?

Best,

**Comment by eugef** [comment]
Hi @gabssnake 

I suggest you can use `res._getHeaders()` to make assertions if header exists and has certain value

**Comment by gabssnake** [comment]
Thank you for your answer.
I was specifically interested in cookies, so ended up using `req.headers.cookie` and `res.cookies`.
