### ISSUE TITLE
Can I test the app directly, instead of an individual route?

### ISSUE THREAD

**Issue by nikoschon** [howardabrams/node-mocks-http#225]
```
describe('Jest setup', () => {
  test('Get all accounts', async () => {
    const request = createRequest({
      method: 'GET',
      url: '/api/accounts',
    });
    const response = createResponse();

    await app(request, response);

    console.log(response._getData());
  });
});
```

The route is hit after the end of test.

**Comment by eugef** [comment]
This depends if you `app()` function returns a promise or not

**Comment by nikoschon** [comment]
forgot to mention this. This is an express app instance `const app = express();`

**Comment by eugef** [comment]
Then it won't work.

You can take a look into `supertest` - it is more suitable to test the whole app.

**Comment by nhooyr** [comment]
Looks like the same issue with testing a `express.Router`. If a route is async, then the router will not wait for the promise to resolve and return early, but not return a promise itself so there's nothing for the test to await on.
