### ISSUE TITLE
@types/express as direct dependency?

### ISSUE THREAD

**Issue by toomuchdesign** [howardabrams/node-mocks-http#226]
The types of this library import `express` and its types [here](https://github.com/howardabrams/node-mocks-http/blob/74440bc6df04fadb8a9755d5c8321e9bdc9c4d2c/lib/index.d.ts#L1) but `@types/express` is declared as devDependencies.

This means that in order to use `node-mocks-http` types, a user must install `@types/express` in its consuming project and ensure express types are aligned with the express version used by `node-mocks-http`.

If `@types/express` were declared as direct dependencies, types should work out of the box. Was this an intended decision?

Thank you for your efforts here!
Greetings

**Comment by eugef** [comment]
Hi @toomuchdesign 

This is done intentionally to prevent installing `@types/express` in projects that do not use Typescript.

If you know a better approach to achieve this - please advise

**Comment by toomuchdesign** [comment]
Thanks @eugef,
I had the same doubt about a project of mine. In my case I decided to pay the price for the extra direct dependency but it's 100% a matter of tradeoffs. I wanted to make sure it was intentional. 👍 

Maybe declaring `@types/express` could be also declared as [`optionaldependencies`](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#optionaldependencies), but this would not represent a big gain.
