### ISSUE TITLE
req.hostname doesn't reflect real hostname

### ISSUE THREAD

**Issue by jereaameli** [howardabrams/node-mocks-http#230]
## Bug

PR #224 introduced a feature where `req.hostname` get's calculated from the `Host` header, but it wrongly truncates it to the 2 upper domains.

For example:

- `example.com` will continue being `example.com` ✅ 
- `mercadolibre.com.ar` will get truncated to `.com.ar` ❌

## Solution

`req.hostname` should reflect exactly the same value as the `Host` header, without the port information if it was included, and all subdomains must be included.

## Reference

For reference, [here](https://github.com/expressjs/express/blob/508936853a6e311099c9985d4c11a4b1b8f6af07/lib/request.js#L427) we can see how Express calculates the `hostname` value.

**Comment by eugef** [comment]
Hi @jereaameli, thank you for reporting the issue, the fix will be released in the next version
