### ISSUE TITLE
request.getHeader() missing?

### ISSUE THREAD

**Issue by rhazegh** [howardabrams/node-mocks-http#240]
Thank you for this great library. I am using this to test my Nextjs API routes. It has been working so far until I decided to send some http headers in the request. 

In the test file:
```javascript
const { req, res } = createMocks({
  method: "GET",
  headers: { language: "en" },
});
```

When I try to retrieve the headers in the API end point:
```javascript
export const handler = async (req, res) => {
  // ...
  const { language } = req.headers;     // <-- This works
  const lang2 = req.getHeader("language");  // <-- This throws an error: TypeError: req.getHeader is not a function
  // ...
}
```

According to Nodejs documentation https://nodejs.org/api/http.html#http_request_getheader_name, it seems that `request.getHeader(name)` should be available. 

Is this something that can be added to node-mocks-http?

**Comment by eugef** [comment]
Hi @rhazegh you are right, `req.getHeader()` should be also available.

Here is the PR with a fix https://github.com/howardabrams/node-mocks-http/pull/241

**Comment by rhazegh** [comment]
@eugef Fantastic. Thanks for the quick fix.

BTW, I found out that Nextjs's request object for API routes is an instance of Node's [http.IncomingMessage](https://nodejs.org/api/http.html#http_class_http_incomingmessage) which supports `request.headers` so ended up not using `request.getHeader()`. Thanks again.

**Comment by eugef** [comment]
you are welcome
