### ISSUE TITLE
Please tag 1.10.1

### ISSUE THREAD

**Issue by kaplanlior** [howardabrams/node-mocks-http#250]
Thanks for maintaining node-mocks-http :+1: 

Can you tag 3497bc5b28858ea3c37471a4034536d9c9834168 as 1.10.1 ?
(or maybe you did it locally and didn't push the tag)

**Comment by eugef** [comment]
Hi @kaplanlior new tag & release are created https://github.com/howardabrams/node-mocks-http/releases/tag/v1.10.1
