### ISSUE TITLE
Why is baseUrl non-empty?

### ISSUE THREAD

**Issue by smalllong** [howardabrams/node-mocks-http#252]
In real apps, baseUrl can be empty and path be non-empty when not using router middlewares. But in this mocks, baseUrl is always non-empty when path is not empty. I can not pass an empty baseUrl to override it as it always fallback to path. Why is that?

**Comment by eugef** [comment]
Hi @smalllong please provide a code example of how are you passing an empty `baseUrl`

**Comment by smalllong** [comment]
`var createRequest = require('node-mocks-http').createRequest;

console.log(createRequest({
    baseUrl: '',
    path: '/category/request',
    method: 'POST',
  }))`

**Comment by eugef** [comment]
Could you try the following:

```
const req = createRequest({
    path: '/category/request',
    method: 'POST',
});
  
req._setBaseUrl('');

// or 

re.baseUrl = ''; 
```

**Comment by smalllong** [comment]
That may be working, although I don't think that's the correct solution
