### ISSUE TITLE
Testing Next.js, can't get _getJSONData()

### ISSUE THREAD

**Issue by benbagley** [howardabrams/node-mocks-http#255]
Hey,

I'm currently creating an application using Next and have built some API endpoints.

I'm testing the following file

```
import { NextApiRequest, NextApiResponse } from "next";
import { getConfig } from "../../utils/config/config";
import { getStoriesList } from "../../utils/api/getStoriesList";

export default async (req: NextApiRequest, res: NextApiResponse) => {
  if (req.method !== "GET") {
    res.status(405).json({
      statusCode: 405,
      message: "Method not allowed"
    });

    return;
  }

  const config = getConfig();

  res.status(200).json(
    await getStoriesList(
      {
        cursor: req.query.cursor as string
      },
      config,
      req.cookies
    )
  );
};
```

I'm trying to test these lines,
```
  if (req.method !== "GET") {
    res.status(405).json({
      statusCode: 405,
      message: "Method not allowed"
    });

    return;
  }
```

However, I cannot seem to get the json response, i.e. the statusCode or message.

As for the testing suite I'm using jest and have the following code using this package as a base for the request method

```
import { createMocks, RequestMethod } from "node-mocks-http";
import type { NextApiRequest, NextApiResponse } from "next";
import handler from "./paginate";

describe("Paginate", () => {
  function mockRequestResponse(method: RequestMethod = "GET") {
    const { req, res }: { req: NextApiRequest; res: NextApiResponse } = createMocks({ method });

    return { req, res };
  }

// other tests

  test("that if the request is not GET and 405 throw an error", async () => {
    const { req, res } = mockRequestResponse("POST");

    await handler(req, res);

    expect(res.statusCode).toBe(405);

    expect(res._getJSONData()).toEqual({
      statusCode: 405,
      message: "Method not allowed",
    });
  });
});
```

I get the following error on `expect(res._getJSONData()).toEqual({`
```
TS2339: Property '_getJSONData' does not exist on type 'NextApiResponse '
```

Any help here would be great, although i am not using express, all posts I see in regards to testing nextjs typescript api requests I see this package so thought I would give it a shot.

**Comment by suciptoid** [comment]
I'm using this snipped on my test

```ts
import type { NextApiHandler, NextApiRequest, NextApiResponse } from "next";
import { createRequest, createResponse, RequestOptions } from "node-mocks-http";

type ApiRequest = NextApiRequest & ReturnType<typeof createRequest>;
type APiResponse = NextApiResponse & ReturnType<typeof createResponse>;

export const testHandler = async (
  handler: NextApiHandler,
  options: RequestOptions
) => {
  const req = createRequest<ApiRequest>(options);
  const res = createResponse<APiResponse>();

  await handler(req, res);
  return res;
};
```

And the test code
```ts
test("test node-mock-http", async () => {
  const res = await testHandler(handler, { method: "GET" });

  expect(res.statusCode).toBe(200);
  expect(res._getJSONData()).toEqual({
    message: "ok",
  });
});
```

**Comment by mtoranzoskw** [comment]
I was dealing with typing... your snippet worked like a charm...
The key is type definition:
```ts
type ApiRequest = NextApiRequest & ReturnType<typeof createRequest>;
type APiResponse = NextApiResponse & ReturnType<typeof createResponse>;
```

**Comment by qrtp** [comment]
> suciptoid

Thanks @suciptoid it worked for me too 👍

**Comment by arturenault** [comment]
Almost works for me, but because the types don't match perfectly I get errors with headers. It looks like `node-mocks-http` uses direct indexing for headers, while Next uses `request.headers.get`. I get this error:

```
    TypeError: request.headers.get is not a function
```

**Comment by juanantona** [comment]
Really interesting thread! I think that you could just do:
```js
import type { NextApiHandler, NextApiRequest, NextApiResponse } from "next";
import { createRequest, createResponse, RequestOptions } from "node-mocks-http";

const req = createRequest<NextApiRequest>(options);
const res = createResponse<NextApiResponse>();
```
Since `createRequest` and `createResponse` already extend the types that receive as the docs show:
```js
export function createRequest<T extends Request = Request>(options?: RequestOptions): MockRequest<T>;
export function createResponse<T extends Response = Response>(options?: ResponseOptions): MockResponse<T>;
```

On the other hand, @arturenault to test the `request.headers.get` method I'm just mocking it:
```js
const req = createRequest<NextApiRequest>(options);
const getHeaders = jest.fn();
when(getHeaders).expectCalledWith('authorization').mockReturnValue('token');

req.headers.get = getHeaders;
```
And on my side 😅 , I'm having trouble with `res.headers.set` since `headers` it seems to be not present in the `res` object.

**Comment by kkankala** [comment]
I'm unable to test or mock `res.setPreviewData`. I get `TypeError: res.setPreviewData is not a function` error.

**Comment by sahilrajput03** [comment]
> I'm using this snippet on my test
> 
> ```ts
> import type { NextApiHandler, NextApiRequest, NextApiResponse } from "next";
> import { createRequest, createResponse, RequestOptions } from "node-mocks-http";
> 
> type ApiRequest = NextApiRequest & ReturnType<typeof createRequest>;
> type APiResponse = NextApiResponse & ReturnType<typeof createResponse>;
> 
> export const testHandler = async (
>   handler: NextApiHandler,
>   options: RequestOptions
> ) => {
>   const req = createRequest<ApiRequest>(options);
>   const res = createResponse<APiResponse>();
> 
>   await handler(req, res);
>   return res;
> };
> ```
> 
> And the test code
> 
> ```ts
> test("test node-mock-http", async () => {
>   const res = await testHandler(handler, { method: "GET" });
> 
>   expect(res.statusCode).toBe(200);
>   expect(res._getJSONData()).toEqual({
>     message: "ok",
>   });
> });
> ```

Actually they types just returns `any`:

![image](https://user-images.githubusercontent.com/31458531/192481928-810c898b-7dba-47d1-86cc-6fa715b63188.png)

![image](https://user-images.githubusercontent.com/31458531/192482078-cd993743-472a-44ca-ad0e-5001ae480fe4.png)


Can we please have types for this library?

**Comment by rhzs** [comment]
You can also simplify without custom method by using `createMocks<ApiRequest, APiResponse>({})`.

```
import { NextApiRequest, NextApiResponse } from "next";
import { createRequest, createResponse, createMocks } from "node-mocks-http";

export type ApiRequest = NextApiRequest & ReturnType<typeof createRequest>;
export type APiResponse = NextApiResponse & ReturnType<typeof createResponse>;

const { req, res } = createMocks<ApiRequest, APiResponse>({
    method: "POST",
    body: {
        resetToken: "user forgot password token",
        newPassword: "newPassword",
        repeatNewPassword: "newPassword",
    },
});
```
