### ISSUE TITLE
stale "json" method for response 

### ISSUE THREAD

**Issue by chitreshd** [howardabrams/node-mocks-http#26]
JSON method for response object in node-mocks-http accepts two arguments: status code and data object. The latest express implementation, only accepts one argument: data object. The problem with this discrepancy is that, if you call "status" and "json" method in a chain(while using node-mocks-http), the status code set through status method is overwritten in json method.

**Comment by JohnnyEstilles** [comment]
@chitreshd, your assessment is not entire accurate. While the [Express 4.x docs](http://expressjs.com/api.html#res.json) show the following signature for the `.json()` method:
```js
res.json([body]);
```
Express actually still accepts the following deprecated signatures (and displays a deprecation message):
```js
res.json(body, status);
res.json(status, body);
```
Likewise, the `mockReponse.json()` method can be called using any of these signatures. Therefore, the following code (if I understood your use case correctly) should generate the correct status code.
```js
var response = httpMocks.createResponse();

response.status(999).json({ key: 'value' });
assert(response.statusCode === 999);
```
AFAICT,  `mockResponse.json()` is working as expected.

**Comment by JohnnyEstilles** [comment]
@chitreshd, I have verified that `mockResponse.json()` works as expected. If you have any additional questions or comments feel free to reopen this issue.
