### ISSUE TITLE
@types/express 3.17.15 -> Request/Response mismatch 

### ISSUE THREAD

**Issue by Hourglasser23** [howardabrams/node-mocks-http#266]
**@types/express** upgrade to latest **3.17.15** would be appreciated as types mismatch (current 3.17.7 to 3.17.15) is creating following error

Error:
Argument of type 'MockRequest<Request<ParamsDictionary, any, any, ParsedQs>>' is not assignable to parameter of type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
 Types of property 'app' are incompatible. Type 'Application' is not assignable to type 'Application<Record<string, any>>'.

**Comment by Hourglasser23** [comment]
I wanted to create pull request but I do not have permissions to publish branch

**Comment by eugef** [comment]
Hi @Hourglasser23 you can fork this repo and then create a PR.

**Comment by Hourglasser23** [comment]
> Hi @Hourglasser23 you can fork this repo and then create a PR.

Oh, my brain washed with New Year 🤯 PR created, thanks

**Comment by eugef** [comment]
No problem :) thanks for your contribution
