### ISSUE TITLE
Importing produces ESlint warning `import/named`

### ISSUE THREAD

**Issue by alvarlagerlof** [howardabrams/node-mocks-http#269]
I have this line of code to import a few functions form this library.

```tsx
import { createMocks, createRequest, createResponse } from 'node-mocks-http'
```

However, that gives me an ESLint warning like: 

createResponse not found in 'node-mocks-http'eslint[import/named](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/named.md)

I something wrong with the exports, or am I importing incorrectly? Thanks!

**Comment by eugef** [comment]
What version of the lib do you use?

Does the code actually work if you ignore eslint warning

**Comment by alvarlagerlof** [comment]
> What version of the lib do you use?

1.12.2

> Does the code actually work if you ignore eslint warning

Yes

**Comment by eugef** [comment]
Then I think it might be a problem with eslint configuration.

Library package.json doesn't contain `module` entry, so "[import/named](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/named.md)" rule should not be applied.

**Comment by eugef** [comment]
That I don't know.

**Comment by alvarlagerlof** [comment]
Maybe I'll have to ignore the error or something. I'm guessing you have no plans to move to ESM?

**Comment by eugef** [comment]
Not in the nearest future
