### ISSUE TITLE
Async support?

### ISSUE THREAD

**Issue by jayeshgangadharan** [howardabrams/node-mocks-http#28]
Can i use node-mocks-http for testing async? for eg: I have this in my router which can be reached through GET /category/list

var getData = function (req, res) {
    MongooseCategory.find({}, function (err, docs) {
        if (!err) {
            res.json(200, { categories: docs });
        } else {
            res.json(500, { message: err });
        }
    });
};

In the test
var response = httpMocks.createResponse();
getData(request, response);
console.log(response._getData());

but the response does not contain the json (response comes back later after a few seconds). How can i test this? Any help is much appreciated.

**Comment by knowmad** [comment]
We're having this issue as well. It looks like the problem has been addressed via events. I found this pull request from early last year -- https://github.com/howardabrams/node-mocks-http/pull/11. However, as you'll see in my comment, I've been unable to get it working. Hope you'll have better luck!

**Comment by frankcash** [comment]
:-1:  has anyone got this to work with async yet?  I will try to meddle more but it'd be awesome if someone else has.

**Comment by jayeshgangadharan** [comment]
Nope I couldn't, so moved over to [Supertest](https://www.npmjs.com/package/supertest) with sinon for mock/stub.

**Comment by howardabrams** [comment]
Not really sure how at this point with really changing its simple interface. I'll be curious if your able to come up with a solution.

**Comment by JohnnyEstilles** [comment]
@jayeshgangadharan, I know I'm relatively new to this project, but I would like to give my two cents on this issue.

1. Your idea to use `sinon` is spot on. That is exactly what you should be using. That said, just like you used `sinon` with `Supertest` you could have also done so with `node-mocks-http` as well.
2. I believe that within your unit tests you should be testing your code and not third-party code that make async calls to server-side services. Libraries like `sinon` exist to help us stub and simulate their behavior.

I think my two cents require more explanation ...

In your example I assume `MongooseCategory` is a Mongoose model. I also assume that, in your test, you are not testing the behavior of the Mongoose `model#find()` method. As Mongoose consumers, we presume the Mongoose folks have already done that for us. What you are, in fact, testing is your code's within the `model#find()` method's callback.

The async call to `MongooseCategory.find()` can be easily simulated with `sinon`, while still using our `response` mock.

In the test below I simulate the two possible conditions in the callback (with and without an error);
```js
var MongooseCategory = {
  find: function() {}
}

afterEach(function() {
  MongooseCategory.find.restore();
})

it('shoud return doc', function() {
  var request = mocks.createRequest();
  var response = mocks.createResponse();

  // simulate MongooseCategory.find() returns a doc
  sinon.stub(MongooseCategory, 'find', function(query, callback) {
    callback(null, [{ name: 'value' }]);
  });

  getData(request, response);
  console.log(response._getData());
});

it('shoud return error', function() {
  var request = mocks.createRequest();
  var response = mocks.createResponse();

  // simulate MongooseCategory.find() returns an error
  sinon.stub(MongooseCategory, 'find', function(query, callback) {
    callback('error message');
  });

  getData(request, response);
  console.log(response._getData());
});
```
I just ran this test using the current version of `node-mocks-http` and this was the result:
```
{"categories":[{"name":"value"}]}
  ✓ shoud return doc 
{"message":"error message"}
  ✓ shoud return error 

  2 passing (10ms)
```
The concept employed above can be easily extrapolated and transferred to any use-case involving async calls.

`node-mocks-http` intends to simulate the behavior of `request` and `response` objects for the purpose of testing your Express route handlers/middleware. It is not opinionated and presumes nothing about the code being tested.

It is therefore, IMHO, each developer's responsibility to mock/stub calls to any async functions/methods that are not part of the unit under test.

As-is, `node-mocks-http` can be used to test async code, with a little help from libraries like `sinon`. Providing any other support for testing async code is outside the scope of our project.

**Comment by JohnnyEstilles** [comment]
@howardabrams ... I'm closing this issue for now. If anyone believes it requires further discussion, please feel free to reopen.

**Comment by chmanie** [comment]
This my (first) take on simple async testing with this library:

https://gist.github.com/da3c150cc8fda254a1a5

**Comment by JohnnyEstilles** [comment]
@chmanie, that's a nice solution. Thanks for sharing. The solution I provided above intended to use `node-mocks-http` as-is. That said, in the next version of the project (see our roadmap in issue #54) the mocked response object will be an event emitter (much like Express' response object), so your solution could easily be implemented.

Thanks again for sharing! :-)

**Comment by hallucynogenyc** [comment]
I don't understand where the trouble is. What's wrong with the out-of-the-box way:

```javascript
var mock_res = httpMocks.createResponse({
    eventEmitter: require('events').EventEmitter
  });
```

**Comment by hallucynogenyc** [comment]
What's wrong with this out-of-the-box solution?

```javascript
mock_res = httpMocks.createResponse({
    eventEmitter: eventEmitter
  });
```

**Comment by chmanie** [comment]
Some of the functions (e.g. `res.json()` and `res.emit()`) don't call `res.end()` per default.

**Comment by JohnnyEstilles** [comment]
@chmanie, thanks for point that out. We are currently aware of some the current inconsistencies in the implementation. We're in the process of overhauling `node-mocks-http`, and the `2.0` version should correct all of these inconsistencies. If there's something in particular that you need urgently fixed in the `1.x` track just open a new issue and let us know what you need. We will be happy to accommodate you.

**Comment by romanlv** [comment]
Solution described in #159 seems easiest to implement 

here is typescript example, works with next.js
https://gist.github.com/romanlv/c12c2541212110968bc92ba19b176d1c
