### ISSUE TITLE
mockResponse.statusCode should default to 200 not -1

### ISSUE THREAD

**Issue by JohnnyEstilles** [howardabrams/node-mocks-http#37]
@howardabrams, as per [your comment](https://github.com/howardabrams/node-mocks-http/pull/36#issuecomment-76617249) on PR #36, I understand the intent of your project is to maintain compatibility between both the Node and Express APIs. (Thanks again for sharing ... this is an awesome mock).

That being the case, it should be noted that Node's `http.ServerResponse` class initializes the `statusCode` property to `200` (see [code here](https://github.com/joyent/node/blob/master/lib/_http_server.js#L125)). This means that `mockResponse.statusCode` should likewise default to `200` (instead of `-1`).

Since Express extends Node's `http.ServerResponse` class (see [code here](https://github.com/strongloop/express/blob/master/lib/response.js#L38)), the status code of its response object will also default to `200`

Changing the default `statusCode` in `mockResponse` to `200` will make that behavior consistent with both Node and Express.

I understand this will be a "breaking" change, but in the interest of maintaining compatibility with both Node and Express I think issue should be addressed. I will submit a PR for your consideration later today.

**Comment by JohnnyEstilles** [comment]
Submitted PR #38 to address this issue.

**Comment by howardabrams** [comment]
Most excellent. I will grab all your changes and bundle them into version
1.2.5 ...

**Comment by JohnnyEstilles** [comment]
Awesome! Looking forward to v1.2.5. :-)
