### ISSUE TITLE
Add .type() to mockResponse

### ISSUE THREAD

**Issue by JohnnyEstilles** [howardabrams/node-mocks-http#39]
I suggest we add the Express `res.type()` method to `mockResponse` as described in [http://expressjs.com/4x/api.html#res.type](http://expressjs.com/4x/api.html#res.type).

**Comment by JohnnyEstilles** [comment]
@howardabrams, the Express 3.x docs show that `res.contentType()` was an alias of `rest.type()`. The Express 4.x docs no longer do. Should we implement `res.contentType()` for backwards compatibility?

**Comment by howardabrams** [comment]
I don't see why not. It shouldn't hurt or break current tests.

**Comment by JohnnyEstilles** [comment]
Implemented via #42
