### ISSUE TITLE
Need events

### ISSUE THREAD

**Issue by jaslo** [howardabrams/node-mocks-http#47]
I am trying to use this library to make calls into my express app, but the data is returned with "res.send" and "res.end".  So in my caller, I try to listen to those emitters, but they are all stubbed out!  Why not use the real event module?

req = mocks.createRequest(..)
resp = mocks.createResponse(..)
resp.on('end', function() { check resp._getData });
app.handle(req,resp); // call into express

**Comment by JohnnyEstilles** [comment]
@jaslo, you're absolutely correct. This is a duplicate issue (see #17).

We intend to make both `mockRequest` and `mockResponse` event emitters, to better mimic the Express objects. This work is slated for our next major release. Please follow #17 for updates on this issue.

**Comment by jaslo** [comment]
I forked the code simply substituted "require('events').EventEmitter" instead of the mockEventEmitter.
It worked great for my purposes!  If you want me to submit a pull request, I can.

**Comment by JohnnyEstilles** [comment]
I really appreciate the offer, but there's no need for a PR. The current code base already supports using a custom event emitter.

You can replaced the `mockEventEmitter` by passing an `eventEmitter` option to `.createcreateResponse()`.

```js
var httpMocks = require('node-mocks-http');
var myEventEmitter = require('events').EventEmitter;

res = mocks.createResponse({ eventEmitter: myEventEmitter });
```

**Comment by JohnnyEstilles** [comment]
Duplicate issue (#17) ... closing for now. If need further assistance feel free to reopen the issue. Thanks!

**Comment by jaslo** [comment]
Thanks, that's a much better solution than creating a new branch.
