### ISSUE TITLE
mockResponse.send() does not call .end()

### ISSUE THREAD

**Issue by estilles** [howardabrams/node-mocks-http#49]
`mockResponse.send()` should call `.end()`
- Express' implementation of `response.send()` calls `.end()`
- Since `.end()` is not never called `._isEndCalled()` returns `false` after calls to `.send()`

**Comment by JohnnyEstilles** [comment]
Deferring implementation until `v1.3`. Correct implementation of `.send()` requires features being added in `v1.3`.

**Comment by JohnnyEstilles** [comment]
Deferring implementation until v2.0. Implementation will introduce BREAKING changes.

**Comment by shermany** [comment]
How are you supposed to use this module without this functionality? Assuming your handler function makes _any_ kind of async call, and the response will be written in a callback, you can't call the handler function and just start making asserts against your mock `request` object.

I looked at the source, and ended up with something like this:
```
//...
      response.on('end', function() {
        assert.equal(202, response.statusCode);
        done();
      });
//... more tests
```
but alas the 'end' event is never emitted, and my test just times out.

**Comment by JohnnyEstilles** [comment]
@shermany, this will work out of the box in `2.0`. In `1.x` you can do it by using your own event emitter (i.e. Node's `EventEmitter`). In the meantime try using the code below.

```js
var httpMocks = require('node-mocks-http');
var response = httpMocks.createResponse({
  EventEmitter: require('events').EventEmitter;
});

//...
      response.on('end', function() {
        assert.equal(202, response.statusCode);
        done();
      });
//... more tests
```

**Comment by forwardadvance** [comment]
It doesn't appear to emit events correctly at the moment, even with the above.

    var req = mocks.createRequest({
      body: demoUser,
      session:{}
    });
    var res = mocks.createResponse({
      EventEmitter: require('events').EventEmitter
    });
    sessionController.create(req, res);
    res.on('end', function() {
      console.log("W00t!!!!!");
      next();
    });

W00t!!! is never output, even though res.end() is called.

**Comment by hatchan** [comment]
This should also apply to `mockResponse.json()`. The `_isEndCalled` always returns false.

**Comment by danallen88** [comment]
@forwardadvance - A couple things you've probably gleaned from other threads, but: 

`var res = mocks.createResponse({
  EventEmitter: require('events').EventEmitter
});`

should be 

`var res = mocks.createResponse({
  eventEmitter: require('events').EventEmitter
});`
Note the camel casing on the `eventEmitter` property.

It's probably worth moving your event handler for the `'end'` event before making a call to `sessionController.create()` to eliminate possible timing issues.

Regardless, I agree this is still an issue in that even with these, 'end' is not getting called.

**Comment by basit1327** [comment]
Still facing this issue in 2021? tried in all manners with res.send()  res.write() res.end()  but .end() event never called
