### ISSUE TITLE
'end' or 'close' event or callback for response

### ISSUE THREAD

**Issue by jzaefferer** [howardabrams/node-mocks-http#6]
The example in the readme assumes that the response is sync. Since I'm testing a wrapper around an actual http API, the response is async, so I need an event or callback. Neither "end" nor "close" seem to get emitted, and I don't think I'm missing something, since the end method doesn't bother.

I can provide a patch, but would like to get confirmation that it would get merged etc.

**Comment by GiordanoArman** [comment]
@eugef I noticed that the response.end() callback you find in the official Node.js docs

https://nodejs.org/docs/latest-v12.x/api/http.html#http_response_end_data_encoding_callback

is not triggered. Is it possible to have the mock response object mimick the native response on this matter?

**Comment by eugef** [comment]
Hi @GiordanoArman PR is always welcome.

Meanwhile you can manually trigger `response.end()` callback in the testst this way:

```
import httpMocks from 'node-mocks-http';

const req = httpMocks.createRequest();
const res = httpMocks.createResponse();
const next = () => {};

someMiddleware(req, res, next);

res.end();

```

**Comment by GiordanoArman** [comment]
@eugef ok, thanks, would you rather have this fix on a fork of the 1.x branch or master branch?

**Comment by eugef** [comment]
Master branch

**Comment by GiordanoArman** [comment]
ok, great :) will this fix be released in a 1.x version or when you release version 2?

**Comment by eugef** [comment]
I assume this feature won't introduce a breaking change, so it would be possible to release as a minor version.

**Comment by GiordanoArman** [comment]
ok, do you perhaps need to add me as collaborator somehow in order for me to push the changes? I'm stuck with auth errors, whether I use personal tokens or SSH keys... been a while since last time I used GitHub via command line lol

**Comment by eugef** [comment]
Hi @GiordanoArman, please fork the repo and do all the changes there, Then you can create a PR https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
