### ISSUE TITLE
res.send vs res.json

### ISSUE THREAD

**Issue by tamlyn** [howardabrams/node-mocks-http#63]
According to [the Express docs](http://expressjs.com/api.html#res.json) calling `res.send({foo: 'bar'})` is identical to calling `res.json({foo: 'bar'})`. However in the [mock response](https://github.com/howardabrams/node-mocks-http/blob/ae6c785d5a741a517e0f6a4602ba580e21a6add4/lib/mockResponse.js#L228), these are handled differently with only `json` setting the content type header and stringifying the data.

**Comment by JohnnyEstilles** [comment]
@tamlyn, you're absolutely correct. This is schedule to be fixed in `2.0`. If you need this urgently let me know and I will push a fix for it this weekend.

**Comment by tamlyn** [comment]
Thanks. It's OK, I've worked around it but it caused me a bit of confusion. Glad to hear you're on it.

**Comment by JohnnyEstilles** [comment]
No worries. Since this issue will be resolved in `2.0` (issue #54) I will close this issue for now. Feel free to re-open it of you need to.
