### ISSUE TITLE
createRequest ignores path option

### ISSUE THREAD

**Issue by aaronjameslang** [howardabrams/node-mocks-http#68]
If a path but no url is supplied to createRequest, the path is ignored.

This should be an easy fix, I'll submit a pull request when I've fixed it.

**Comment by aaronjameslang** [comment]
https://github.com/howardabrams/node-mocks-http/pull/69

**Comment by howardabrams** [comment]
Guess we can close this now, eh? ;-)

**Comment by aaronjameslang** [comment]
Yeh, thanks. Who's responsible for closing issues? Should I have done it
when the pull request was accepted?

**Comment by howardabrams** [comment]
Sure! Go for it. Thanks again for helping.
