### ISSUE TITLE
Response does not emit events

### ISSUE THREAD

**Issue by TravelingTechGuy** [howardabrams/node-mocks-http#73]
Tried following instructions and samples - to no avail - the response object never fires an event. Not `end`, not `send`.

Here's a simple function (using Express 4.*):

```
export function getServiceHealth(req, res) {
  let message = 'service has been up for ' + process.uptime() + ' seconds!';
  res.status(200).send(message);
}
```

And here's my test. It times out. 

```
import {EventEmitter} from 'events';
import httpMock from 'node-mocks-http';
import {getServiceHealth} from '../../lib/controllers/health/';

describe('Service health integration tests', () => {
  it('should get health', done => {
    let req = httpMock.createRequest({url: '/health'});
    let res = httpMock.createResponse({EventEmitter: EventEmitter});
    getServiceHealth(req, res);
    res.on('end', () => {
      console.log(res._getData());
      done();
    });
    res.on('send', () => {
      console.log(res._getData());
      done();
    });
    //setTimeout(() => {console.log(res._getData()); done();}, 1000);
  });
});
```

I resorted to the commented line at the end, that fires `done()` using setTimeout. Obviously, not the right way to go. What do I have to do to get the event triggered on `res`?
(BTW, when I log `res` it gets the right status and data)

**Note:** on the off chance that this is some ES6 `import` shenanigan, I tried this:

```
let res = httpMock.createResponse({EventEmitter: require('events').EventEmitter});
```

Same result.

**Comment by jshcrowthe** [comment]
@TravelingTechGuy I had the same issue here today. The issue for me turned out to be that the property `EventEmitter` actually needed to be camel case (So: `eventEmitter`). 

The docs give the following example:
```javascript
var res = httpMocks.createResponse({
  EventEmitter: require('events').EventEmitter
});
```

I believe it needs to be updated to

```javascript
var res = httpMocks.createResponse({
  eventEmitter: require('events').EventEmitter
});
```

**Comment by TravelingTechGuy** [comment]
Tried it - still not being triggered, and I get a timeout :(

**Comment by jshcrowthe** [comment]
Good call, I just refactored some of my code to account for that.

**Comment by howardabrams** [comment]
Is this behavior acceptable?

**Comment by jshcrowthe** [comment]
@howardabrams I'm fine with it seeing as it is documented (thanks for that!). Passing an `eventEmitter` can be useful but not having one at all just seems inconsistent with the concept of a `response` so if I had my way I'd love to see there being a functional default.

More than anything I'd recommend that the docs giving an example of this have the `eventEmitter` properly camel cased to avoid confusion.

**Comment by TravelingTechGuy** [comment]
I second what @jshcrowthe said: proper (working?) examples would help.
I would like to see a working event emitter (i.e., not dependent on the call order), but I can work with it as it is right now - again, proper documentation will prevent future questions.
But I do thank you for all your efforts @howardabrams!

**Comment by howardabrams** [comment]
If you have some time to give me a pull request on the documentation change
you'd like to see, I would appreciate it (as I love having this project be
a community affair).

**Comment by jshcrowthe** [comment]
@howardabrams I'll try and put together a PR to fix the docs and possibly introduce a standard `eventEmitter` as a default.

**Comment by rakeshongithub** [comment]
can someone help me to createResponse for negative scenario.

**Comment by Downchuck** [comment]
Ouch! I got caught in this one - I did see in the manual a warning about event emitter. Lost some time to figuring it out. createMocks(request_stuff, { eventEmitter: require('events').EventEmitter})
