### ISSUE TITLE
Assertion errors not logged in console

### ISSUE THREAD

**Issue by dsteinbach** [howardabrams/node-mocks-http#87]
The following mocha code will timeout instead of displaying the assertion error:

```
  it('tests things', function(done){
    var response = httpMocks.createResponse({eventEmitter: require('events').EventEmitter});
    var request  = httpMocks.createRequest({
      method: 'GET',
      url: '/'
    });
    response.on('end', function() {
      [].should.have.length(2);
      done();
    });

    subject.handle(request, response);
  });
```

**Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.**

If I set it to validate against length 0, the test passes fine.

**Comment by marcosmercuri** [comment]
I have the same problem. Did you solve it in some way?

**Comment by marcosmercuri** [comment]
For future reference:

You need to try/catch the assertion in the callback, and call 'done' with the error (yeah, pretty crappy):

```javascript
    response.on('end', () => {
      try {
        expect(response.statusCode).to.eq(200)
         done()
      } catch (error) { 
         done(error)
      }
    })
```
