### ISSUE TITLE
How do you use mock-express.js 

### ISSUE THREAD

**Issue by BenCoffman** [howardabrams/node-mocks-http#91]
The library works great, but since my controller uses express and has a few extra libraries injected in via app.use like express-validator, the request fails out because it doesn't have a few of the methods.

It looks like someone set it up for an express request, but there is no documentation on how to use it.

**Comment by acanimal** [comment]
Any feedback? I'm in the same situation.

**Comment by samjbmason** [comment]
Im also in the same situation anyone getting anywhere with it?

**Comment by samjbmason** [comment]
@howardabrams Any small piece of info to get started would be really helpful and really appreciated.

**Comment by acanimal** [comment]
Hi, next is a piece of code to test a middleware I'm working on responsible to make redirections depending on the requests. Hope it helps.

Note I have also stubbed `request.get()` because it is used within my `subdmainRedirector` middleware.

```javascript
import httpMocks from 'node-mocks-http';
import { expect } from 'chai';
import sinon from 'sinon';
import redirectorMiddleware from './subdomainRedirector';

describe('SubdomainRedirector middleware...', () => {
  const extraData = {
    countryCode: 'es',
    countryLanguage: 'es',
    subdomainCountryCode: 'es',
    subdomainCountryLanguage: 'es',
    lang: 'es',
  };
  let request;
  let response;
  let sandbox;

  beforeEach(() => {
    request = httpMocks.createRequest({
      method: 'GET',
      url: '/',
    });
    response = httpMocks.createResponse();
    sandbox = sinon.sandbox.create();
  });

  afterEach(() => {
    sandbox.restore();
  });

  it('Should do not redirect if URL is an IP...', () => {
    sandbox.stub(request, 'get')
      .withArgs('host')
      .returns('127.0.0.1');
    request.protocol = 'http';
    request.extraData = extraData;
    request.hostname = '127.0.0.1';

    redirectorMiddleware(request, response, () => {});

    expect(response.statusCode).to.be.equal(200);
  });
 ...
```

**Comment by samjbmason** [comment]
@acanimal Im guessing you don't have access to methods on the `request` though e.g `.acceptedLanguages()` as you're just using the plain `createRequest`?

**Comment by acanimal** [comment]
ough!!! you are right. Not much help then :(

**Comment by acanimal** [comment]
I think that part is not finished yet. The  `mock-express.js` module tries to include `mock-response` which doesn't exists.
