### ISSUE TITLE
Support res.format

### ISSUE THREAD

**Issue by jmnsf** [howardabrams/node-mocks-http#94]
[`res.format`](http://expressjs.com/en/api.html#res.format) is super useful for having an endpoint that handles multiple Accept headers. Without this, these endpoints can't be tested.

**Comment by Vishal-Joshi** [comment]
Same issue! When can we expect a resolution for it? I am stuck because of it and my controller cant be tested without its support?

Did you find another alternative @jmnsf meanwhile fix arrives?

**Comment by jmnsf** [comment]
@Vishal-Joshi I've mocked the behaviour, temporarily. Not a very elegant solution since it is heavily coupled to the formats Object provided, but works for the time being.

```javascript
context('given an HTML request', () => {
      beforeEach(() => httpMocks.createResponse().format = formats => formats.html());
```

Doing it in `httpMocks` requires a reference to the Request headers from the mockResponse that isn't there atm.

**Comment by Vishal-Joshi** [comment]
What is this 'formats' object? @jmnsf

**Comment by jmnsf** [comment]
The argument to `res.format`, has all your handlers per format.

**Comment by Vishal-Joshi** [comment]
No, I am asking about the 'formats' object which you are assigning to httpMocks.createResponse().format?

**Comment by howardabrams** [comment]
I could really use some help on this one. Would either of you like to attempt a pull request with your approach? Tests to explain how it should be used would be great too!
