### ISSUE TITLE
Files sending, how to test multiparty?

### ISSUE THREAD

**Issue by Britskiy** [howardabrams/node-mocks-http#97]
Hello, im using **multiparty** extension for nodejs.
How can i test my app with **node-mocks-http** ? 

I try 

```
files {'file','data:image/png;base64,iVB....'}
files {'file',Payload data from curl'} 
```

nothing(

can you show how to do that?
**Thnks for the great testing tool!!!**

**Comment by MaksymMPanchyshyn** [comment]
@Britskiy Hi, did you find a way to do this?

**Comment by Britskiy** [comment]
@MaksymMPanchyshyn, At the moment, no, but I think I just did not understand until the end because later I tried to do this by extending the Postman in Chrome and I have all happened, I applied form-data with field type of file and it worked maybe later I'll be back to this question and be sure to accomplish your goal here about your experience or do you do it)

**Comment by jwhitmarsh** [comment]
Sorry to comment on an old issue, but did anyone get anywhere with this? @MaksymMPanchyshyn or @Britskiy ?
