### ISSUE TITLE
Typescript definitions file

### ISSUE THREAD

**Issue by 19majkel94** [howardabrams/node-mocks-http#99]
Could you make the Typescript definitions file (*.d.ts) of this module?
https://www.typescriptlang.org/docs/handbook/writing-declaration-files.html

It's a great tool for writing in TS or JS because it provide intellisens, code completion, error checking before compilation and other amazing stuffs which makes developer life much easier ;)

**Comment by howardabrams** [comment]
Since I'm not familiar enough, could you try to and make a Pull Request? Thanks!

**Comment by LJNielsenDk** [comment]
There are some here: https://github.com/cj-wang/mean-start/blob/master/server/types/node-mocks-http/index.d.ts

They're not mine and I'm not sure how complete or correct they are.

**Comment by corinnaerin** [comment]
Here you go! I submitted a pull request: https://github.com/howardabrams/node-mocks-http/pull/134

**Comment by davidhouweling** [comment]
@howardabrams when will the npm package be updated to reflect this change?

**Comment by arryon** [comment]
I second that request. Why the delay, since the typings have already been merged? Would really like to use them in my projects

**Comment by maxsommer** [comment]
I know this issue is really old – but in my opinion more relevant than ever.

**Comment by nhooyr** [comment]
New version has been published guys! 2 months ago!

https://www.npmjs.com/package/node-mocks-http

**Comment by beevk** [comment]
How can I import the types? It's not available as @types/node-mocks-http.

**Comment by corinnaerin** [comment]
> 
> 
> How can I import the types? It's not available as @types/node-mocks-http.

You don't have to import them separately, they're bundled with the package.
